
# catalog-info.yml
# This file contains metadata for backstage
# Read more about available fields and annotations:
# https://github.com/tradeshift/backstage
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins-java-client-api
  description: |
    Repository for keeping jenkins-java-client-api
  annotations:
    github.com/project-slug: Tradeshift/jenkins-java-client-api    # GitHub project name

spec:
  type: other
  owner: platform-ops
  lifecycle: experimental